PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX research: <http://www.example.edu/research/>

SELECT ?property
WHERE {
    ?property rdf:type rdf:Property ;
              rdfs:domain research:author .
}